apiVersion: v1
kind: Service
metadata:
  name: mysql8
  namespace: todo
  labels:
    app: mysql8
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: tcp
  selector:
    app: mysql8
