apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: todo
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1 
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: eureka:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 40000
