spring:
  profiles:
    active: dev

todo:
  guid:
    # 时间比特位, 支持运行34年
    timeBits: 30
    # 机器比特位, 支持集群最大重启次数262,143次
    workerBits: 18
    # 序列比特位, 支持单节点每秒生成65,534个ID
    seqBits: 15
    # 相对时间基点
    epochStr: 2016-09-20
    # RingBuffer Size扩容参数, 可提高UID生成的吞吐量, 默认为3
    boostPower: 3
    # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
    paddingFactor: 50
