@startuml token and refresh token
'https://plantuml.com/sequence-diagram

autonumber
alt 登录
用户 -> 前端: 点击登录
前端 -> 后端认证授权服务: 请求登录（用户名、密码和是否记住我)
后端认证授权服务 -> 后端认证授权服务: 认证与授权
后端认证授权服务 --> 前端: token信息/错误信息
前端 -> 前端: 本地存储token信息(可选：错误时不处理)
前端 --> 用户: 登录成功后页面/错误信息

用户 -> 前端: 后续业务请求
前端 -> 后端资源服务: 组装Authentication协议头(type + 一个空格 + access token)(备注：这里忽略了token认证过程)
后端资源服务 --> 前端: 资源内容
前端 --> 用户
end

alt refresh token(保持会话)(token超时)
用户 -> 前端: 需要授权业务请求
前端 -> 后端认证授权服务: 授权验证
后端 --> 前端: token失效，返回错误和一个固定错误码，如：401错误码
前端 -> 前端: 拦截错误码,401错误码进行token刷新
前端 -> 后端认证授权服务: 组装refresh token请求
    alt 刷新成功
        后端认证授权服务 -> 后端认证授权服务: 获取token信息
        后端认证授权服务 --> 前端: token信息
        前端 -> 前端: 更新本地token信息;重试之前请求（可选)
        前端 --> 用户: 业务成功，结果展示
    end
    alt 刷新失败
        后端认证授权服务 -> 后端认证授权服务: refresh token过期
        后端认证授权服务 --> 前端: 失败
        前端 --> 用户: 跳转到登录页面
    end

end
@enduml