apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
    namespace: todo
  name: gateway-clusterip
  namespace: todo
spec:
  ports:
  - name: service0
    port: 40001               
    protocol: TCP            
    targetPort: 40001           
  selector:                   
    app: gateway
  type: ClusterIP  
