apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: todo
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:${tag}
        imagePullPolicy: Never
        ports:
        - containerPort: 40001
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap
              key: SPRING_PROFILES_ACTIVE
          name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE    
