apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: todo
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: todo
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: conf-dir
              mountPath: /etc/nginx/conf.d
            - name: site-dir
              mountPath: /app/webroot
            - name: log-dir
              mountPath: /app/applog/nginx/logs/

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: conf-dir
          hostPath:
            path: /appdata/app/webroot/conf.d
            type: Directory
        - name: site-dir
          hostPath:
            path: /appdata/app/webroot/
            type: Directory
        - name: log-dir
          hostPath:
            path: /appdata/app/applog/nginx/logs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: todo
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 80
        nodePort: 80
        targetPort: 81
        protocol: TCP
        name: eureka
  selector:
    app: nginx
