version: '3.3'
services:
  eureka:
    container_name: eureka
    restart: always 
    image: todo-eureka:${tag}
    ports:
      - "40000:40000"
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    #  - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  gateway:
    container_name: gateway
    restart: always 
    image: todo-gateway:${tag}
    ports:
      - "40001:40001"
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    #  - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.19.143.30:40000/eureka/	  
      - SPRING_CLOUD_CLIENT_IPADDRESS=172.19.143.30

  auth:
    container_name: auth
    restart: always 
    image: todo-auth:${tag}
    ports:
      - "40002:40002"
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    #  - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.19.143.30:40000/eureka/	 
      - SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME=username
      - SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME=username
      - SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_URL=jdbc:mysql://172.19.143.30:60000/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      - SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_URL=jdbc:mysql://172.19.143.30:60000/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      - SPRING_CLOUD_CLIENT_IPADDRESS=172.19.143.30


  task:
    container_name: task
    restart: always 
    image: todo-task:${tag}
    ports:
      - "40004:40004"
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    #  - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.19.143.30:40000/eureka/	
      - SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME=username
      - SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME=username
      - SPRING_CLOUD_CLIENT_IPADDRESS=172.19.143.30

  usercenter:
    container_name: usercenter
    restart: always 
    image: todo-usercenter:${tag}
    ports:
      - "40003:40003"
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    #  - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.19.143.30:40000/eureka/	  
      - SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME=username
      - SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME=username
      - SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_URL=jdbc:mysql://172.19.143.30:60000/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      - SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_URL=jdbc:mysql://172.19.143.30:60000/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      - SPRING_CLOUD_CLIENT_IPADDRESS=172.19.143.30

