apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: todo
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
