apiVersion: v1
kind: ConfigMap
metadata:
  name: task-configmap
  namespace: todo
data:
  SPRING_PROFILES_ACTIVE: prod
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-clusterip:40000/eureka/
  SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME: username
  SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME: username
  SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_URL: jdbc:mysql://mysql8:3306/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
  SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_URL: jdbc:mysql://mysql8:3306/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  namespace: todo
spec:
  selector:
    matchLabels:
      app: task
  replicas: 1
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: todo-task:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 40004
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: task-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: task-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: task-configmap
                  key: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME

            - name: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: task-configmap
                  key: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME

            - name: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_URL
              valueFrom:
                configMapKeyRef:
                  name: task-configmap
                  key: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_URL

            - name: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_URL
              valueFrom:
                configMapKeyRef:
                  name: task-configmap
                  key: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_URL
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task
    namespace: todo
  name: task-clusterip
spec:
  ports:
    - name: service0
      port: 40004
      protocol: TCP
      targetPort: 40004
  selector:
    app: task
  type: ClusterIP
