spring:
  application:
    name: usercenter
  shardingsphere:
    datasource:
      names: master,slave0
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.126.184:3306/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username:
        password:
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 600000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        asyncInit: true
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.126.184:3306/todo_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username:  
        password:  
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 600000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        asyncInit: true
    masterslave:
      master-data-source-name: master
      name: ms
      slave-data-source-names: slave0
    props:
      sql:
        show: true

#  redis:
#    database: 2
#    host: 172.16.126.184
#    port: 6379
#    password:
#    timeout: 5000s  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8  #连接池中的最大空闲连接
#        max-wait: 30 #连接池最大阻塞等待时间（使用负值表示没有限制)
#        min-idle: 0  #连接池中的最小空闲连接
