apiVersion: v1
kind: Service
metadata:
  labels:
    app: task
    namespace: todo
  name: task-clusterip
spec:
  ports:
  - name: service0
    port: 40004
    protocol: TCP
    targetPort: 40004
  selector:
    app: task
  type: ClusterIP
