apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-clusterip
  namespace: todo
spec:
  ports:
  - name: service0
    port: 40002
    protocol: TCP
    targetPort: 40002
  selector:
    app: auth
  type: ClusterIP
