apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: todo
  labels:
    app: eureka
  name: eureka-clusterip
spec:
  ports:
  - name: service0
    port: 40000               
    protocol: TCP            
    targetPort: 40000           
  selector:                   
    app: eureka
  type: ClusterIP  
