spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
          # 默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled: true
          # 表示将请求路径的服务名配置改成小写  因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/api/'+serviceId+'/**'"
          filters:
            - StripPrefix=2
      httpclient:
        connect-timeout: 6000
        response-timeout: 120s
    sentinel:
      scg:
        fallback:
          response-body: '{"code":403,"message":"限流了"}'
          mode: response

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:40002/getPublicKey'

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:40000/eureka/
    registry-fetch-interval-seconds: 10

todo:
  gateway:
    publicKey: /public.txt