apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-clusterip
  namespace: todo
spec:
  ports:
  - name: service0
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
