apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter
  namespace: todo
spec:
  selector:
    matchLabels:
      app: usercenter
  replicas: 1
  template:
    metadata:
      labels:
        app: usercenter
    spec:
      containers:
      - name: usercenter
        image: todo-usercenter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 40003
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: usercenter-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: usercenter-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE   
        - name: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: usercenter-configmap
              key: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_USERNAME   
              
        - name: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME
          valueFrom:
            configMapKeyRef:
              name: usercenter-configmap
              key: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_USERNAME
              
        - name: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_URL
          valueFrom:
            configMapKeyRef:
              name: usercenter-configmap
              key: SPRING_SHARDINGSPHERE_DATASOURCE_MASTER_URL
              
        - name: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_URL
          valueFrom:
            configMapKeyRef:
              name: usercenter-configmap
              key: SPRING_SHARDINGSPHERE_DATASOURCE_SLAVE0_URL
      
