apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
    namespace: todo
  name: auth-clusterip
spec:
  ports:
  - name: service0
    port: 40002
    protocol: TCP
    targetPort: 40002
  selector:
    app: auth
  type: ClusterIP
